# yaml-language-server: $schema=https://github.com/Azure/deployment-environments/releases/download/2022-11-11-preview/manifest.schema.json
name: AI_Foundry_SPA_Frontend
version: 1.0.0
summary: Frontend infrastructure for AI Foundry SPA application
description: |
  Deploys the frontend infrastructure for the AI Foundry SPA application including:
  - Azure Static Web App for SPA hosting with built-in CDN and SSL
  - Application Insights for frontend monitoring and analytics
  - Integration with existing Log Analytics Workspace for consolidated logging
  
  This template creates a modern, scalable frontend hosting solution with
  automatic HTTPS, global distribution, and comprehensive monitoring.

runner: Bicep
templatePath: ../../modules/frontend.bicep

parameters:
  - id: applicationName
    name: Application Name
    description: Name used for resource naming (e.g., aibox)
    type: string
    required: true
    default: aibox
    
  - id: environmentName
    name: Environment Name
    description: Environment identifier (dev, staging, prod)
    type: string
    required: true
    default: dev
    allowed:
      - dev
      - staging
      - prod
      
  - id: location
    name: Azure Region
    description: Azure region for resource deployment
    type: string
    required: true
    default: eastus2
    allowed:
      - centralus
      - eastus
      - eastus2
      - westus
      - westus2
      
  - id: logAnalyticsWorkspaceName
    name: Log Analytics Workspace Name
    description: Name of existing Log Analytics Workspace for consolidated logging
    type: string
    required: true
    
  - id: logAnalyticsResourceGroupName
    name: Log Analytics Resource Group
    description: Resource Group containing the Log Analytics Workspace
    type: string
    required: true
