#!/usr/bin/env pwsh
<#
.SYNOPSIS
Deploy the frontend of AI Foundry SPA to Azure Static Web App

.DESCRIPTION
This script deploys the frontend portion of the AI Foundry SPA to an existing Azure Static Web App.
Both StaticWebAppName and ResourceGroupName are required parameters.

This script is designed to work with Node.js versions > 20 by providing alternatives to the 
Azure Static Web Apps CLI (SWA CLI) which is not compatible with Node.js > 20.

For local development, use 'npm run dev' instead.

.PARAMETER StaticWebAppName
The name of the Azure Static Web App to deploy to. Required.

.PARAMETER ResourceGroupName
The name of the resource group containing the Static Web App. Required.

.PARAMETER BackendUrl
The backend Function App URL to configure (optional - will update .env for dev environment)

.PARAMETER SkipBuild
Skip the npm build step if the application is already built

.EXAMPLE
./deploy-frontend-spa-code.ps1 -StaticWebAppName "stapp-aibox-fd-dev-eus2" -ResourceGroupName "rg-ai-foundry-spa-frontend-dev-eus2"

.EXAMPLE
./deploy-frontend-spa-code.ps1 -StaticWebAppName "stapp-aibox-fd-dev-eus2" -ResourceGroupName "rg-ai-foundry-spa-frontend-dev-eus2" -BackendUrl "https://func-ai-foundry-spa-backend-dev-eus2.azurewebsites.net/api"

.EXAMPLE
./deploy-frontend-spa-code.ps1 -StaticWebAppName "my-custom-static-web-app" -ResourceGroupName "my-rg" -SkipBuild
#>

param(
    [Parameter(Mandatory = $true)]
    [string]$StaticWebAppName,
    
    [Parameter(Mandatory = $true)]
    [string]$ResourceGroupName,
    
    [Parameter(Mandatory = $false)]
    [string]$BackendUrl,
    
    [Parameter(Mandatory = $false)]
    [switch]$SkipBuild
)

# Set error action preference
$ErrorActionPreference = "Stop"

Write-Host "🚀 AI Foundry SPA - Frontend Deployment" -ForegroundColor Green -BackgroundColor Black
Write-Host "=======================================" -ForegroundColor Green

# Change to project root (go up one level from deploy-scripts)
Set-Location (Join-Path $PSScriptRoot "..")

# Check if Azure CLI is installed and logged in
Write-Host "🔍 Checking Azure CLI authentication..." -ForegroundColor Yellow
try {
    $account = az account show --output json 2>$null | ConvertFrom-Json
    Write-Host "✅ Azure CLI authenticated as: $($account.user.name)" -ForegroundColor Green
    Write-Host "📋 Subscription: $($account.name) ($($account.id))" -ForegroundColor Cyan
}
catch {
    Write-Error "❌ Azure CLI not authenticated. Please run 'az login' first."
    exit 1
}

Write-Host "☁️ Deploying to Azure Static Web App" -ForegroundColor Yellow
Write-Host "   Target Static Web App: $StaticWebAppName" -ForegroundColor Cyan
Write-Host "   Target Resource Group: $ResourceGroupName" -ForegroundColor Cyan

# Verify the Static Web App exists
Write-Host "🔍 Verifying Static Web App '$StaticWebAppName' in resource group '$ResourceGroupName'..." -ForegroundColor Yellow
try {
    $staticWebApp = az staticwebapp show --name $StaticWebAppName --resource-group $ResourceGroupName --output json | ConvertFrom-Json
    Write-Host "✅ Static Web App found: $($staticWebApp.name)" -ForegroundColor Green
}
catch {
    Write-Error "❌ Static Web App '$StaticWebAppName' not found in resource group '$ResourceGroupName'!"
    Write-Host "💡 To create the infrastructure first, run:" -ForegroundColor Yellow
    Write-Host "   az deployment sub create --template-file infra/main-orchestrator.bicep --parameters infra/dev-orchestrator.parameters.bicepparam --location eastus2" -ForegroundColor White
    exit 1
}

# Update environment configuration for dev environment
Write-Host "🔧 Updating frontend configuration for dev environment..." -ForegroundColor Yellow

# Create dev environment file with hardcoded dev values
$envContent = @"
# Dev Environment Configuration - Generated by deployment script
VITE_BACKEND_URL=$($BackendUrl -replace '^$', 'http://localhost:7071/api')
VITE_USE_BACKEND=true
VITE_PUBLIC_MODE=false

# AI Foundry Configuration (Dev Environment)
VITE_AI_FOUNDRY_AGENT_NAME=AI in A Box
VITE_AI_FOUNDRY_AGENT_ID=asst_dH7M0nbmdRblhSQO8nIGIYF4
VITE_AI_FOUNDRY_PROJECT_URL=https://ai-foundry-dev-eus.services.ai.azure.com/api/projects/firstProject
VITE_AI_FOUNDRY_ENDPOINT=https://ai-foundry-dev-eus.azureml.net
VITE_AI_FOUNDRY_DEPLOYMENT=gpt-4

# Azure Static Web App Configuration
VITE_STATIC_WEB_APP_NAME=$StaticWebAppName

# Environment Settings
VITE_ENV=dev
NODE_ENV=development
"@

Set-Content -Path "src/frontend/.env.dev" -Value $envContent
Write-Host "✅ Dev environment configuration created" -ForegroundColor Green

# Build frontend if not skipped
if (-not $SkipBuild) {
    Write-Host "🔨 Building frontend application for dev environment..." -ForegroundColor Yellow
    
    # Navigate to frontend directory
    Push-Location "src/frontend"
    try {
        # Install dependencies
        Write-Host "📦 Installing dependencies..." -ForegroundColor Cyan
        npm install
        if ($LASTEXITCODE -ne 0) {
            Write-Error "❌ npm install failed!"
            exit 1
        }
        
        # Build the application for dev environment
        Write-Host "🏗️ Building application for dev..." -ForegroundColor Cyan
        $env:NODE_ENV = "development"
        
        # Try the dev build script first, fall back to standard build if it fails
        npm run build:dev
        if ($LASTEXITCODE -ne 0) {
            Write-Warning "⚠️ Dev build failed, trying standard build..."
            npm run build
        }
        
        if ($LASTEXITCODE -ne 0) {
            Write-Error "❌ Frontend build failed!"
            exit 1
        }
        
        Write-Host "✅ Frontend build completed for dev environment!" -ForegroundColor Green
    }
    finally {
        Pop-Location
    }
}
else {
    Write-Host "⏭️ Skipping frontend build..." -ForegroundColor Yellow
}

# Verify the build output exists
$buildPath = "src/frontend/dist"
if (-not (Test-Path $buildPath)) {
    Write-Error "❌ Build output not found at '$buildPath'! Please build the application first."
    exit 1
}

Write-Host "📁 Using build output from: $buildPath" -ForegroundColor Cyan

# Deploy to Static Web App
Write-Host "🚀 Deploying frontend files to Azure Static Web App..." -ForegroundColor Yellow

# Get deployment token for the Static Web App
Write-Host "🔑 Getting deployment token..." -ForegroundColor Cyan
$deploymentToken = az staticwebapp secrets list --name $StaticWebAppName --resource-group $ResourceGroupName --query "properties.apiKey" --output tsv

if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrEmpty($deploymentToken)) {
    Write-Error "❌ Failed to get deployment token for Static Web App!"
    exit 1
}

# Deploy using Node.js-compatible method (alternative to SWA CLI for Node.js >20)
Write-Host "🚀 Deploying to Static Web App using Node.js-compatible method..." -ForegroundColor Yellow

# Check Node.js version first
$nodeVersion = node --version 2>$null
if ($nodeVersion) {
    $nodeMajorVersion = [int]($nodeVersion -replace 'v(\d+)\..*', '$1')
    Write-Host "📋 Node.js version: $nodeVersion (Major: $nodeMajorVersion)" -ForegroundColor Cyan
}
else {
    Write-Host "⚠️  Could not detect Node.js version" -ForegroundColor Yellow
    $nodeMajorVersion = 999 # Assume incompatible
}

# Main deployment logic
$deploymentSuccess = $false

# Try SWA CLI first if Node.js is compatible
if ($nodeMajorVersion -le 20) {
    Write-Host "✅ Node.js version is compatible with SWA CLI, using standard deployment..." -ForegroundColor Green
    
    # Use SWA CLI since Node.js is compatible
    try {
        # Check if SWA CLI is available
        $swaVersion = npx --version 2>$null
        if ($swaVersion) {
            Write-Host "📦 Using npx to run SWA CLI..." -ForegroundColor Cyan
            npx @azure/static-web-apps-cli@latest deploy $buildPath --deployment-token $deploymentToken --env "dev"
            $deploymentSuccess = ($LASTEXITCODE -eq 0)
        }
        else {
            Write-Host "❌ npx not available" -ForegroundColor Red
        }
    }
    catch {
        Write-Host "⚠️  SWA CLI deployment failed, trying alternative..." -ForegroundColor Yellow
    }
}
else {
    Write-Host "⚠️  Node.js version $nodeVersion is not compatible with SWA CLI (>20)" -ForegroundColor Yellow
}

# If primary method failed, try alternatives
if (-not $deploymentSuccess) {
    Write-Host "🔄 Trying alternative deployment methods..." -ForegroundColor Yellow
    
    # Method 1: Use curl if available (most reliable)
    if (Get-Command curl -ErrorAction SilentlyContinue) {
        Write-Host "📦 Creating deployment package..." -ForegroundColor Cyan
        
        $tempZipPath = Join-Path $env:TEMP "swa-deployment-$(Get-Date -Format 'yyyyMMdd-HHmmss').zip"
        
        try {
            # Create zip file using PowerShell
            Compress-Archive -Path "$buildPath\*" -DestinationPath $tempZipPath -Force
            
            Write-Host "✅ Deployment package created" -ForegroundColor Green
            
            # Deploy using curl
            Write-Host "🌐 Uploading to Azure Static Web Apps..." -ForegroundColor Cyan
            
            # Get the Static Web App default hostname for deployment endpoint
            $staticWebApp = az staticwebapp show --name $StaticWebAppName --resource-group $ResourceGroupName --output json | ConvertFrom-Json
            $deploymentEndpoint = "https://$($staticWebApp.defaultHostname.Replace('.azurestaticapps.net', '.scm.azurestaticapps.net'))/api/zipdeploy"
            
            Write-Host "   Endpoint: $deploymentEndpoint" -ForegroundColor Gray
            
            $curlArgs = @(
                "--request", "POST"
                "--url", $deploymentEndpoint
                "--header", "Authorization: Bearer $deploymentToken"
                "--header", "Content-Type: application/zip"
                "--data-binary", "@$tempZipPath"
                "--fail"
                "--show-error"
            )
            
            $curlOutput = & curl @curlArgs 2>&1
            
            if ($LASTEXITCODE -eq 0) {
                Write-Host "✅ Deployment completed successfully with curl!" -ForegroundColor Green
                $deploymentSuccess = $true
            }
            else {
                Write-Host "❌ Deployment failed with curl" -ForegroundColor Red
                Write-Host "   Output: $curlOutput" -ForegroundColor Gray
            }
        }
        finally {
            if (Test-Path $tempZipPath) {
                Remove-Item $tempZipPath -Force
            }
        }
    }
    
    # Method 2: Use PowerShell Invoke-RestMethod as fallback
    if (-not $deploymentSuccess) {
        Write-Host "🔄 Trying PowerShell REST API..." -ForegroundColor Yellow
        
        try {
            $tempZipPath = Join-Path $env:TEMP "swa-deployment-$(Get-Date -Format 'yyyyMMdd-HHmmss').zip"
            
            # Create zip file
            Compress-Archive -Path "$buildPath\*" -DestinationPath $tempZipPath -Force
            
            # Get deployment endpoint
            $staticWebApp = az staticwebapp show --name $StaticWebAppName --resource-group $ResourceGroupName --output json | ConvertFrom-Json
            $deploymentEndpoint = "https://$($staticWebApp.defaultHostname.Replace('.azurestaticapps.net', '.scm.azurestaticapps.net'))/api/zipdeploy"
            
            # Prepare headers
            $headers = @{
                "Authorization" = "Bearer $deploymentToken"
                "Content-Type"  = "application/zip"
            }
            
            # Read file as bytes
            $fileBytes = [System.IO.File]::ReadAllBytes($tempZipPath)
            
            Write-Host "🌐 Uploading via PowerShell REST API..." -ForegroundColor Cyan
            
            $null = Invoke-RestMethod -Uri $deploymentEndpoint -Method Post -Headers $headers -Body $fileBytes -ContentType "application/zip"
            
            Write-Host "✅ Deployment completed successfully with PowerShell!" -ForegroundColor Green
            $deploymentSuccess = $true
        }
        catch {
            Write-Host "❌ PowerShell REST API deployment failed" -ForegroundColor Red
            Write-Host "   Error: $($_.Exception.Message)" -ForegroundColor Gray
        }
        finally {
            if (Test-Path $tempZipPath) {
                Remove-Item $tempZipPath -Force
            }
        }
    }
}

if (-not $deploymentSuccess) {
    Write-Host ""
    Write-Host "❌ All deployment methods failed!" -ForegroundColor Red
    Write-Host ""
    Write-Host "🛠️  Alternative deployment options:" -ForegroundColor Yellow
    Write-Host "   1. Use Node.js 18 or 20 for SWA CLI compatibility" -ForegroundColor White
    Write-Host "   2. Deploy via Azure Portal (upload zip file)" -ForegroundColor White
    Write-Host "   3. Use GitHub Actions (recommended for CI/CD)" -ForegroundColor White
    Write-Host "   4. Use Visual Studio Code Azure Static Web Apps extension" -ForegroundColor White
    Write-Host ""
    Write-Error "❌ Failed to deploy to Static Web App!"
    exit 1
}

Write-Host "✅ Frontend files deployed successfully!" -ForegroundColor Green

# Get the static web app URL
Write-Host "🔗 Retrieving Static Web App URL..." -ForegroundColor Yellow
$staticWebsiteUrl = "https://$($staticWebApp.defaultHostname)"

# Clean up temporary dev env file
if (Test-Path "src/frontend/.env.dev") {
    Remove-Item "src/frontend/.env.dev" -Force
}

# Final summary
Write-Host ""
Write-Host "🎉 Frontend deployment completed successfully! 🎉" -ForegroundColor Green -BackgroundColor Black
Write-Host ""
Write-Host "📋 Deployment Summary:" -ForegroundColor Cyan
Write-Host "   Static Web App: $StaticWebAppName" -ForegroundColor White
Write-Host "   Resource Group: $ResourceGroupName" -ForegroundColor White
Write-Host "   Static Web App URL: $staticWebsiteUrl" -ForegroundColor White
Write-Host ""
Write-Host "🌍 Your AI Foundry SPA is now live at:" -ForegroundColor Green
Write-Host "   $staticWebsiteUrl" -ForegroundColor Yellow -BackgroundColor DarkBlue
Write-Host ""

Write-Host "📋 Configuration:" -ForegroundColor Cyan
Write-Host "   Backend URL: $($BackendUrl -replace '^$', 'http://localhost:7071/api (local dev)')" -ForegroundColor White
Write-Host "   AI Foundry: ai-foundry-dev-eus (dev environment)" -ForegroundColor White
Write-Host ""

Write-Host "✨ Frontend deployment complete! ✨" -ForegroundColor Green
