# yaml-language-server: $schema=../manifest.schema.json

name: AI_Foundry_SPA_Backend
summary: Backend Function App for AI Foundry SPA with proxy functionality
description: |
  Deploys a serverless Function App that acts as a proxy between the frontend SPA 
  and AI Foundry services. Includes proper RBAC configuration and monitoring.

runner: Bicep
templatePath: main.bicep

parameters:
  - id: applicationName
    name: Application Name
    description: Name of the application used for resource naming
    type: string
    required: true

  - id: aiFoundryEndpoint
    name: AI Foundry Endpoint
    description: The full endpoint URL for the AI Foundry service
    type: string
    required: true

  - id: aiFoundryInstanceName
    name: AI Foundry Workspace Name
    description: The name of the AI Foundry workspace
    type: string
    required: true

  - id: aiFoundryResourceGroupName
    name: AI Foundry Resource Group Name
    description: The name of the AI Foundry workspace's Resource Group
    type: string
    required: true

  - id: aiFoundryAgentId
    name: AI Foundry Agent ID
    description: The ID of the AI agent to use
    type: string
    required: true

  - id: aiFoundryAgentName
    name: AI Foundry Agent Name
    description: The display name of the AI agent
    type: string
    required: true

  - id: logAnalyticsWorkspaceName
    name: Log Analytics Workspace Name
    description: Name of existing Log Analytics workspace for monitoring
    type: string
    required: true

  - id: logAnalyticsResourceGroupName
    name: Log Analytics Resource Group
    description: Resource group containing the Log Analytics workspace
    type: string
    required: true

  - id: adeName
    name: ADE Name
    description: Name for the Azure Deployment Environment
    type: string
    required: false
    
  - id: devCenterProjectName
    name: DevCenter Project Name
    description: Name of the DevCenter project
    type: string
    required: false
    
  - id: environmentName
    name: Environment Name
    description: Environment name (e.g., dev, staging, prod)
    type: string
    required: false
    default: dev
    
  - id: location
    name: Location
    description: Azure region for resource deployment
    type: string
    required: false
    default: eastus2
