# yaml-language-server: $schema=../manifest.schema.json
name: AI_Foundry_SPA_Frontend
version: 1.0.0
summary: Frontend infrastructure for AI Foundry SPA application
description: Deploys the frontend infrastructure for the AI Foundry SPA application including
runner: Bicep
templatePath: main.bicep

parameters:
  - id: applicationName
    name: Application Name
    description: Name used for resource naming (e.g., aibox)
    type: string
    required: true
         
  - id: logAnalyticsWorkspaceName
    name: Log Analytics Workspace Name
    description: Name of existing Log Analytics Workspace for consolidated logging
    type: string
    required: true
    
  - id: logAnalyticsResourceGroupName
    name: Log Analytics Resource Group
    description: Resource Group containing the Log Analytics Workspace
    type: string
    required: true

  - id: adeName
    name: ADE Name
    description: Name for the Azure Deployment Environment
    type: string
    required: false
    
  - id: devCenterProjectName
    name: DevCenter Project Name
    description: Name of the DevCenter project
    type: string
    required: false
    
  - id: environmentName
    name: Environment Name
    description: Environment name (e.g., dev, staging, prod)
    type: string
    required: false
    default: dev
    
  - id: location
    name: Location
    description: Azure region for resource deployment
    type: string
    required: false
    default: eastus2
